### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by BrandonEchols04** [haylau/srlv5-format#1]
Hi, @haylau! I'm the same person that's helping with the TotK Bingosync generator, and have a few questions concerning another SLRV5 generator I'm working on. I'm making a spreadsheet in the format that this conversion tool requires, and want to convert it to the v5 format when I'm finished. How do I run this program?

Also, once I have that outputted code, I know that I need to put it into a js file and add `bingoGenerator = require("./generators/generator_bases/srl_generator_v5.js");` to the beginning of the file. I know that I then need to add that file to `bingosync/bingosync-app/generators` (at least I _think_). What else do I have to do to implement this generator? I don't need any varients, just a simple slrv5 generator. Where do I put the generator title and modes, etc? The only reason I'm asking _how_ to do it, and not having someone else do it, is because I'll probably want to be able to make more generators in the future.

Thanks,
      Brandon

**Comment by haylau** [comment]
This tool is a command line tool to convert a csv into the long list of goals in js

I can take a look at the bingosync code again in a bit, but copying the other generators is probably enough? you can take a look at the other pull requests too

**Comment by BrandonEchols04** [comment]
@haylau What do I need to copy from the other generators? I know that I need to have the list js file, but what other files are there to copy, if any?
